"""Generate one statically named CUDA kernel per calibration case."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from .manifest import CASES, manifest_document


HEADER = r'''// Generated by conversion_calibration.codegen. Do not hand edit.
#pragma once

#include "bitwidth_benchmark_core.hpp"
#include "lns_decoder_strategies.cuh"
#include "normal32_formats.hpp"
#include "posit_takum_core.hpp"

#include <cuda_runtime.h>
#include <cstddef>
#include <cstdint>

namespace aut::calibration {

struct device_tables {
  const double *lut0;
  const double *lut1;
  const double *lut2;
  const std::uint32_t *prefix_high;
  const normal32::pwl_coeff *pwl;
  const normal32::pwq_coeff *pwq;
};

extern __constant__ double constant_lut[4096];

__device__ __forceinline__ double finite_from_u32(std::uint32_t value) {
  return __hiloint2double(static_cast<int>(0x3ff00000u | (value >> 12)),
                          static_cast<int>(value << 20));
}

__device__ __forceinline__ std::uint32_t op_iadd3(std::uint32_t a,
                                                   std::uint32_t b,
                                                   std::uint32_t c) {
  std::uint32_t out;
  asm volatile("add.u32 %0, %1, %2; add.u32 %0, %0, %3;"
               : "=r"(out) : "r"(a), "r"(b), "r"(c));
  return out;
}
__device__ __forceinline__ std::uint32_t op_lop3(std::uint32_t a,
                                                 std::uint32_t b,
                                                 std::uint32_t c) {
  std::uint32_t out;
  asm volatile("lop3.b32 %0, %1, %2, %3, 0x96;"
               : "=r"(out) : "r"(a), "r"(b), "r"(c));
  return out;
}
__device__ __forceinline__ std::uint32_t op_shf(std::uint32_t a,
                                                std::uint32_t b) {
  std::uint32_t out;
  asm volatile("shf.l.wrap.b32 %0, %1, %1, %2;"
               : "=r"(out) : "r"(a), "r"(b));
  return out;
}
__device__ __forceinline__ std::uint32_t op_imad(std::uint32_t a,
                                                 std::uint32_t b,
                                                 std::uint32_t c) {
  std::uint32_t out;
  asm volatile("mad.lo.u32 %0, %1, %2, %3;"
               : "=r"(out) : "r"(a), "r"(b), "r"(c));
  return out;
}
__device__ __forceinline__ double op_cvt_u32(std::uint32_t value) {
  double out; asm volatile("cvt.rn.f64.u32 %0, %1;" : "=d"(out) : "r"(value));
  return out;
}
__device__ __forceinline__ double op_cvt_s32(std::int32_t value) {
  double out; asm volatile("cvt.rn.f64.s32 %0, %1;" : "=d"(out) : "r"(value));
  return out;
}
__device__ __forceinline__ double op_cvt_f32(float value) {
  double out; asm volatile("cvt.f64.f32 %0, %1;" : "=d"(out) : "f"(value));
  return out;
}
__device__ __forceinline__ double op_fma64(double a, double b, double c) {
  double out; asm volatile("fma.rn.f64 %0, %1, %2, %3;"
                           : "=d"(out) : "d"(a), "d"(b), "d"(c));
  return out;
}
__device__ __forceinline__ float op_fma32(float a, float b, float c) {
  float out; asm volatile("fma.rn.f32 %0, %1, %2, %3;"
                          : "=f"(out) : "f"(a), "f"(b), "f"(c));
  return out;
}

template <int Case> struct decoder;
'''


FOOTER = r'''
template <int Case>
__global__ __launch_bounds__(256) void dot_case_kernel(
    const std::uint32_t *__restrict__ left,
    const std::uint32_t *__restrict__ right, std::size_t count,
    device_tables tables, double *__restrict__ partials) {
  extern __shared__ unsigned char scratch[];
  auto context = decoder<Case>::prepare(tables, scratch);
  double sum = 0.0;
  const auto stride = static_cast<std::size_t>(gridDim.x) * blockDim.x;
  for (auto index = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;
       index < count; index += stride) {
    const auto a = decoder<Case>::decode(left[index], context);
    const auto b = decoder<Case>::decode(right[index], context);
    sum = fma(a, b, sum);
  }
  auto *shared = reinterpret_cast<double *>(scratch + decoder<Case>::shared_bytes);
  shared[threadIdx.x] = sum;
  __syncthreads();
  for (int offset = 128; offset != 0; offset >>= 1) {
    if (threadIdx.x < offset) shared[threadIdx.x] += shared[threadIdx.x + offset];
    __syncthreads();
  }
  if (threadIdx.x == 0) partials[blockIdx.x] = shared[0];
}

struct host_case_info {
  const char *id;
  const char *split;
  const char *group;
  std::size_t decoder_shared_bytes;
};

inline constexpr host_case_info case_info[] = {
CASE_INFO_ROWS
};

inline void launch_case(int index, dim3 grid, dim3 block, cudaStream_t stream,
                        const std::uint32_t *left, const std::uint32_t *right,
                        std::size_t count, device_tables tables, double *partials) {
  const std::size_t shared = case_info[index].decoder_shared_bytes + 256 * sizeof(double);
  switch (index) {
LAUNCH_CASES
  default: break;
  }
}

inline cudaError_t case_attributes(int index, cudaFuncAttributes *attributes) {
  switch (index) {
ATTRIBUTE_CASES
  default: return cudaErrorInvalidValue;
  }
}

} // namespace aut::calibration
'''


def _base_prelude(shared_bytes: int = 0, context: str = "device_tables") -> str:
    return f"  using context = {context};\n  static constexpr std::size_t shared_bytes = {shared_bytes}u;\n  __device__ __forceinline__ static context prepare(device_tables t, unsigned char *) {{ return t; }}\n"


def _integer_body(op: str, count: int, dependency: str) -> str:
    call = {"iadd3": "op_iadd3({a}, 0x9e3779b9u + {i}u, 0x7f4a7c15u)", "lop3": "op_lop3({a}, 0xa5a5a5a5u + {i}u, 0x3c6ef372u)", "shf": "op_shf({a}, {shift}u)", "imad": "op_imad({a}, 1664525u + 2u * {i}u, 1013904223u)"}[op]
    lines: list[str] = []
    if dependency == "chain":
        lines.append("    std::uint32_t v = raw;")
        for i in range(count):
            lines.append("    v = " + call.format(a="v", i=i, shift=(i % 31) + 1) + ";")
        lines.append("    return finite_from_u32(v);")
    else:
        lines.append("    std::uint32_t v0=raw, v1=raw^0x55555555u, v2=raw^0xaaaaaaaau, v3=~raw;")
        for i in range(count):
            lane = i % 4
            lines.append(f"    v{lane} = " + call.format(a=f"v{lane}", i=i, shift=(i % 31) + 1) + ";")
        lines.append("    return finite_from_u32(v0 ^ v1 ^ v2 ^ v3);")
    return "\n".join(lines)


def _fp_body(precision: str, op: str, count: int, dependency: str) -> str:
    typ = "double" if precision == "fp64" else "float"
    seed = "finite_from_u32(raw)" if precision == "fp64" else "static_cast<float>(finite_from_u32(raw))"
    suffix = "64" if precision == "fp64" else "32"
    if dependency == "parallel":
        lines = [f"    {typ} v0={seed},v1={seed}+0.01,v2={seed}+0.02,v3={seed}+0.03;"]
        for i in range(count):
            lane = i % 4
            if op == "fma": lines.append(f"    v{lane}=op_fma{suffix}(v{lane},1.0000001,0.0000001);")
        lines.append("    return static_cast<double>(v0+v1+v2+v3);")
        return "\n".join(lines)
    lines = [f"    {typ} v={seed};"]
    for _ in range(count):
        if op == "fma": lines.append(f"    v=op_fma{suffix}(v,1.0000001,0.0000001);")
        elif op == "add": lines.append("    asm volatile(\"add.rn.f64 %0, %0, %1;\" : \"+d\"(v) : \"d\"(0.0000001));")
        elif op == "mul": lines.append("    asm volatile(\"mul.rn.f64 %0, %0, %1;\" : \"+d\"(v) : \"d\"(1.0000001));")
    lines.append("    return static_cast<double>(v);")
    return "\n".join(lines)


def _numeric_body(source: str, count: int) -> str:
    lines = ["    double sum=0.0;"]
    for i in range(count):
        if source == "u32": expr = f"op_cvt_u32(raw + {i}u)"
        elif source == "s32": expr = f"op_cvt_s32(static_cast<std::int32_t>(raw + {i}u))"
        else: expr = f"op_cvt_f32(__uint_as_float(raw + {i}u))"
        lines.append(f"    sum += {expr};")
    lines.append("    return sum;")
    return "\n".join(lines)


def _mixed_body(p: dict) -> str:
    lines = ["    std::uint32_t v=raw;"]
    for i in range(p["bitops"]): lines.append(f"    v=op_lop3(v,0x9e3779b9u+{i}u,0x7f4a7c15u);")
    lines.append("    double d=0.0;")
    for i in range(p["conversions"]): lines.append(f"    d += op_cvt_u32(v+{i}u);")
    if p["dependency"] == "parallel":
        lines.append("    double a=d,b=d+1.0,c=d+2.0,e=d+3.0;")
        for i in range(p["fmas"]):
            lane = "abce"[i % 4]
            lines.append(f"    {lane}=op_fma64({lane},1.0000001,0.0000001);")
        lines.append("    return a+b+c+e;")
    else:
        for _ in range(p["fmas"]): lines.append("    d=op_fma64(d,1.0000001,0.0000001);")
        lines.append("    return d;")
    return "\n".join(lines)


def decoder(case, index: int) -> str:
    p = case.params
    prelude = _base_prelude()
    body = "    return finite_from_u32(raw);"
    if case.kind == "anchor_bitcast": pass
    elif case.kind == "integer": body = _integer_body(p["op"], p["count"], p["dependency"])
    elif case.kind == "clz":
        lines=["    std::uint32_t v=raw | 1u, out=0;"]
        for i in range(p["count"]): lines.append(f"    out += static_cast<std::uint32_t>(__clz(v ^ (0x9e3779b9u+{i}u)));")
        lines.append("    return finite_from_u32(out ^ raw);"); body="\n".join(lines)
    elif case.kind == "int64":
        lines=["    std::uint64_t v=(static_cast<std::uint64_t>(raw)<<32)|(~raw);"]
        for i in range(p["count"]): lines.append(f"    v=(v << {(i%31)+1}) ^ (v >> {((i+7)%31)+1}) ^ 0x9e3779b97f4a7c15ull;")
        lines.append("    return finite_from_u32(static_cast<std::uint32_t>(v ^ (v>>32)));"); body="\n".join(lines)
    elif case.kind == "numeric": body = _numeric_body(p["source"], p["count"])
    elif case.kind == "numeric_chain":
        cast = "static_cast<float>(raw)" if p["source"] == "u32" else "static_cast<float>(static_cast<std::int32_t>(raw))"
        body=f"    float middle={cast};\n    return static_cast<double>(middle);"
    elif case.kind == "fp": body = _fp_body(p["precision"], p["op"], p["count"], p["dependency"])
    elif case.kind == "mixed": body = _mixed_body(p)
    elif case.kind == "branch":
        inner = _integer_body("imad", p["count"], "chain") if p["body"] == "integer" else _fp_body("fp64", "fma", p["count"], "chain")
        inner = inner.replace("    return ", "    result = ").replace(";\n", ";\n", 1)
        # Rewrite the final assignment safely; the generated inner body has one final return.
        inner = inner.rsplit("    return ", 1)[0] + ("" if "    return " not in inner else "") if False else inner
        # Generate branch bodies directly to avoid brittle textual return rewriting.
        if p["body"] == "integer":
            statements=["      std::uint32_t v=raw;"] + [f"      v=v*1664525u+1013904223u+{i}u;" for i in range(p["count"])] + ["      result=finite_from_u32(v);"]
        else:
            statements=["      double v=finite_from_u32(raw);"] + ["      v=fma(v,1.0000001,0.0000001);" for _ in range(p["count"])] + ["      result=v;"]
        body = "    double result=finite_from_u32(raw);\n    if ((raw & %du)==0u) {\n%s\n    }\n    return result;" % (p["denominator"]-1, "\n".join(statements))
    elif case.kind == "lut":
        bits, loads, memory = p["bits"], p["loads"], p["memory"]
        idx=f"(raw >> {32-bits})"
        if memory == "global": terms=[f"ctx.lut{i}[{idx}]" for i in range(loads)]
        elif memory == "constant": terms=[f"constant_lut[{idx}]" for _ in range(loads)]
        else:
            prelude = f"  struct context {{ const double *table; }};\n  static constexpr std::size_t shared_bytes = {(1<<bits)*8}u;\n  __device__ __forceinline__ static context prepare(device_tables t, unsigned char *scratch) {{ auto *s=reinterpret_cast<double*>(scratch); for(std::size_t i=threadIdx.x;i<{1<<bits}u;i+=blockDim.x) s[i]=t.lut0[i]; __syncthreads(); return {{s}}; }}\n"
            terms=[f"ctx.table[{idx}]" for _ in range(loads)]
        body="    return " + "+".join(terms) + ";"
    elif case.kind == "special":
        op=p["op"]
        body={"exp2":"    return exp2(static_cast<double>(static_cast<std::int32_t>(raw)) * 0x1p-31);", "log2":"    return log2(finite_from_u32(raw));", "sqrt":"    return sqrt(finite_from_u32(raw));", "div_f64":"    return finite_from_u32(raw) / finite_from_u32(raw ^ 0x9e3779b9u);", "div_u32":"    return finite_from_u32(raw / ((raw >> 24) | 1u));"}[op]
    elif case.kind == "latency":
        chains=p["chains"]; lines=[f"    double v{i}=finite_from_u32(raw ^ {i*0x9e3779b9 & 0xffffffff}u);" for i in range(chains)]
        for i in range(p["fmas"]): lines.append(f"    v{i%chains}=op_fma64(v{i%chains},1.0000001,0.0000001);")
        lines.append("    return " + "+".join(f"v{i}" for i in range(chains)) + ";"); body="\n".join(lines)
    elif case.kind == "clz_shift":
        lines=["    std::uint32_t v=raw|1u;"] + [f"    v ^= static_cast<std::uint32_t>(__clz(v ^ {i+1}u));" for i in range(p["clz"])] + [f"    v=op_shf(v,{i+1}u);" for i in range(p["shifts"])] + ["    return finite_from_u32(v);"]; body="\n".join(lines)
    elif case.kind == "real":
        fmt=p["format"]
        if fmt == "raw_fp32": body="    return static_cast<double>(__uint_as_float(raw));"
        elif fmt == "e11m20_shifter": body="    return aut::decoder::words_to_double({raw,0u});"
        elif fmt == "e9m22_branchy": body="    return bitwidth::decode_direct_fp64_branchy<storage::e9m22>(raw);"
        elif fmt == "e9m22_prefix_global":
            body="""    using layout=bitwidth::format_layout_t<storage::e9m22>;
    const auto exponent=(raw>>layout::fraction_bits)&aut::decoder::exponent_mask<layout>();
    const auto fraction=raw&aut::decoder::fraction_mask<layout>();
    if(exponent==0){ auto words=aut::decoder::subnormal_magnitude_words<layout>(fraction); words.high|=(raw>>31)<<31; return aut::decoder::words_to_double(words); }
    const auto prefix=raw>>layout::fraction_bits;
    const auto high=__ldg(ctx.prefix_high+prefix)|(fraction>>(layout::fraction_bits-20));
    return aut::decoder::words_to_double({high,fraction<<(52-layout::fraction_bits)});"""
        elif fmt == "quadnormal32": body="    const double v=static_cast<double>(static_cast<std::int32_t>(raw)); return v*fma(fabs(v),normal32::normal_sigma*normal32::qn_b/(normal32::qn_integer_scale*normal32::qn_integer_scale),normal32::normal_sigma*normal32::qn_a/normal32::qn_integer_scale);"
        elif fmt == "pwlnormal32_16_16": body="    const auto coeff=ctx.pwl[raw>>16]; return fma(static_cast<double>(static_cast<std::int16_t>(raw&0xffffu)),coeff.b,coeff.a);"
        elif fmt == "pwqnormal32_8_24":
            prelude=f"  struct context {{ const normal32::pwq_coeff *table; }};\n  static constexpr std::size_t shared_bytes = {256*24}u;\n  __device__ __forceinline__ static context prepare(device_tables t,unsigned char *scratch) {{ auto *s=reinterpret_cast<normal32::pwq_coeff*>(scratch); s[threadIdx.x]=t.pwq[threadIdx.x]; __syncthreads(); return {{s}}; }}\n"
            body="    const auto bits=raw&0x00ffffffu; const auto local=static_cast<std::int32_t>((bits&0x00800000u)?(bits|0xff000000u):bits); const auto coeff=ctx.table[raw>>24]; const double x=static_cast<double>(local); return fma(x,fma(x,coeff.c,coeff.b),coeff.a);"
        elif fmt == "posit32_es2": body="    return pt::decode_posit<32,2,double>(raw);"
        elif fmt == "takum32_linear": body="    return pt::decode_linear_takum<32,double>(raw);"
        elif fmt == "takum32_log": body="    return pt::decode_log_takum<32,double>(raw);"
        elif fmt == "lns32_r23_reference_exp2": body="    using D=lns_strategy::decoder_context<lns::lns32_r23,bitwidth::compute_kind::fp64,lns_strategy::decoder_kind::reference_exp2>; return lns_strategy::decode_raw<lns::lns32_r23,bitwidth::compute_kind::fp64,lns_strategy::decoder_kind::reference_exp2>(raw,D{});"
        else: raise ValueError(fmt)
    else: raise ValueError(case.kind)
    return f"template <> struct decoder<{index}> {{\n{prelude}  __device__ __forceinline__ static double decode(std::uint32_t raw, context ctx) {{\n{body}\n  }}\n}};\n"


def render() -> str:
    pieces=[HEADER]
    for i, case in enumerate(CASES): pieces.append(decoder(case,i))
    rows=[]; launches=[]; attrs=[]
    for i, case in enumerate(CASES):
        rows.append(f'  {{"{case.case_id}", "{case.split}", "{case.group}", decoder<{i}>::shared_bytes}},')
        launches.append(f"  case {i}: dot_case_kernel<{i}><<<grid,block,shared,stream>>>(left,right,count,tables,partials); break;")
        attrs.append(f"  case {i}: return cudaFuncGetAttributes(attributes, dot_case_kernel<{i}>);")
    footer = (FOOTER.replace("CASE_INFO_ROWS", "\n".join(rows))
              .replace("LAUNCH_CASES", "\n".join(launches))
              .replace("ATTRIBUTE_CASES", "\n".join(attrs)))
    return "".join(pieces) + footer


def write(output: Path, manifest_output: Path) -> None:
    text=render()
    output.parent.mkdir(parents=True,exist_ok=True)
    output.write_text(text,encoding="utf-8")
    document=manifest_document(); document["generated_header_sha256"]=hashlib.sha256(text.encode()).hexdigest()
    manifest_output.parent.mkdir(parents=True,exist_ok=True)
    manifest_output.write_text(json.dumps(document,indent=2,sort_keys=True)+"\n",encoding="utf-8")


def main() -> None:
    parser=argparse.ArgumentParser(); parser.add_argument("--output",type=Path,default=Path("generated/conversion_calibration_cases.cuh")); parser.add_argument("--manifest",type=Path,default=Path("generated/conversion_calibration_manifest.json")); args=parser.parse_args(); write(args.output,args.manifest)


if __name__ == "__main__": main()
